app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_home_page:
    path: /
    controller: App\Controller\homeController::home

app_search_results:
    path: /search
    controller: App\Controller\SearchController::page

app_login:
    path: /login
    controller: App\Controller\login.php::home

app_add_vehicle:
    path: /add-vehicle/{b}/{m}/{y}
    controller: App\Controller\VehicleController.php::createVehicle
    defaults:
        b: "NA"
        m: "NA"
        y: 0