app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_home_page:
    path: /
    controller: App\Controller\HomeController::home

app_search_results:
    path: /search
    controller: App\Controller\SearchController::page

app_tire_guide:
    path: /tire-guide
    controller: App\Controller\tireGuideController::page