app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_home_page:
    path: /
    controller: App\Controller\homeController::home

app_search_results:
    path: /search
    controller: App\Controller\SearchController::page

app_login:
    path: /ergerg
    controller: App\Controller\login.php::home